# Generated by Django 2.2.2 on 2019-08-07 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ruling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500000, null=True)),
                ('title', models.CharField(max_length=500000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('important_ruling', models.BooleanField(default=False)),
                ('positive_ruling', models.BooleanField()),
                ('ruling_no', models.CharField(max_length=150, null=True)),
                ('mf_library_no', models.CharField(max_length=150, null=True)),
                ('authority', models.ManyToManyField(to='rulingscanner.Authors')),
                ('important_by_user', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='tag', to='rulingscanner.Tag')),
                ('type_of_tax', models.ManyToManyField(default=None, related_name='tax_type', to='rulingscanner.TaxType')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ruling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rulingscanner.Ruling')),
            ],
        ),
    ]
